name: AntiHealthIndicator
author: Bram
description: A plugin that prevents hackers and modders from seeing the health of other players.
website: https://github.com/Bram1903/AntiHealthIndicator
main: com.deathmotion.antihealthindicator.AHIBukkit
version: ${version}
api-version: '1.13'
folia-supported: true
load: POSTWORLD
commands:
  AntiHealthIndicator:
    description: Base command for AntiHealthIndicator.
    aliases:
      - ahi
permissions:
  AntiHealthIndicator.Notify:
    description: "This permission allows players to be notified when an update is found."
    default: op
  AntiHealthIndicator.Bypass:
    description: "This permission prevents the player from receiving spoofed data."
    default: op
  AntiHealthIndicator.Debug:
    description: "This permission allows players to see debug messages."
    default: op
depend:
  - packetevents